CarritoCompras/Models/Producto.cs
using CarritoCompras.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarritoCompras.Models {
    public class Producto
    {
        public int Id { get; set; }
        [Required(ErrorMessage = ErrorMsgs.ErrorRequerido)]
        [StringLength(25, MinimumLength = 2, ErrorMessage = ErrorMsgs.ErrorDeLenght)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = ErrorMsgs.ErrorRequerido)]
        [StringLength(140, MinimumLength = 10, ErrorMessage = ErrorMsgs.ErrorDeLenght)]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = ErrorMsgs.ErrorRequerido)]
        [DataType(DataType.Currency)]
        [Range(0.01, double.MaxValue, ErrorMessage = ErrorMsgs.ErrorMenorACero)]
        [Display(Name ="Precio unitario")]
        public double PrecioVigente { get; set; }

        public bool Activo { get; set; } = true;
        
        public Categoria Categoria { get; set; }
        [Display(Name ="Categoria")]
        [Required]
        public int CategoriaId { get; set; }
        
        public List<StockItem> Stockitems { get; set; }

    }
}

CarritoCompras/Controllers/AccountsController.cs
using CarritoCompras.Data;
using CarritoCompras.Models;
using CarritoCompras.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarritoCompras.Controllers
{
    public class AccountsController : Controller
    {
        private readonly MiContexto _miContexto;
        private readonly UserManager<Usuario> _userManager;
        private readonly SignInManager<Usuario> _signInManager;

        public AccountsController(MiContexto micontexto, 
            UserManager<Usuario> userManager, 
            SignInManager<Usuario> signInManager)
        {
            this._miContexto = micontexto;
            this._userManager = userManager;
            this._signInManager = signInManager;
        }

       [HttpGet]
       public IActionResult RegistroUsuario()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult RegistrarEmpleado()
        {
            return View("RegistroUsuario");
        }

        [HttpPost]
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> RegistrarEmpleado(string email)
        {
            
            if (ModelState.IsValid)
            {
                Usuario usr1 = new Usuario()
                {
                    Email = email,
                    UserName = email
                };
                var resultadoCreateUser = await _userManager.CreateAsync(usr1, "Password1!");

                if (resultadoCreateUser.Succeeded)
                {
                    await _userManager.AddToRoleAsync(usr1, "Empleado");
                    return base.RedirectToAction("Create", "Usuarios", new { id = usr1.Id });
                }


            }
            return View();
        }




        [HttpPost]
        public async Task<IActionResult> RegistroUsuario(Registrar modelo)
        {

            if (ModelState.IsValid)
            {
                Usuario usr1 = new Cliente()
                {
                    Email = modelo.Email,
                    UserName = modelo.Email
                };

                var resultadoCreateUser = await _userManager.CreateAsync(usr1, modelo.Password);

                if (resultadoCreateUser.Succeeded)
                {
                    await _userManager.AddToRoleAsync(usr1, "Cliente");
                    await _signInManager.SignInAsync(usr1, true);
                    return base.RedirectToAction("Create", "Clientes", new { id = usr1.Id });
                }

                foreach(var error in resultadoCreateUser.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

            }

            return View(modelo);
        }

        public async Task<IActionResult> EmailDisponible(string email)
        {
            var usuario = await _userManager.FindByEmailAsync(email);

            if(usuario == null)
            {
                return Json(true);
            }
            else
            {
                return Json($"El correo {email} ya está siendo utilizado");
            }
        }
        [HttpGet]
        public IActionResult IniciarSesion(string returnurl)
        {
            TempData["returnUrl"] = returnurl;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> IniciarSesion(Login modelo)
        {
            //tratamiento al modelo 

            if (ModelState.IsValid)
            {
                var resultado = await _signInManager.PasswordSignInAsync(modelo.NombreUsuario, modelo.Password, modelo.Recordarme, false);

                if (resultado.Succeeded)
                {
                    var returnl = TempData["returnUrl"] as string;
                    if (!string.IsNullOrEmpty(returnl))
                    {
                        return Redirect(returnl);
                    }
                   
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError(string.Empty, "Inicio de sesión incorrecto.");

                return View(modelo);
            }
            return View();
        }

        public async Task<IActionResult> CerrarSesion()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

CarritoCompras/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarritoCompras.Data;
using CarritoCompras.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarritoCompras.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly MiContexto _context;

        public CategoriasController(MiContexto context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categorias.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        [Authorize(Roles="Empleado")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var exists = _context.Categorias.FirstOrDefault(acc => acc.Nombre == categoria.Nombre);
                if (exists == null)
                {
                    _context.Add(categoria);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("Nombre", "No se puede agregar categorías existentes.");
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion")] Categoria categoria)
        {
            if (id != categoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        private bool CategoriaExists(int id)
        {
            return _context.Categorias.Any(e => e.Id == id);
        }
    }
}

CarritoCompras/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarritoCompras.Data;
using CarritoCompras.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarritoCompras.Controllers
{
    public class ProductosController : Controller
    {
        private readonly MiContexto _context;

        public ProductosController(MiContexto context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            var miContexto = _context.Productos.Include(p => p.Categoria);
            return View(await miContexto.ToListAsync());
        }
        public async Task<IActionResult> MostrarProductosPorCategoria(int? id)
        {
            var miContexto = _context.Productos.Where(p => p.CategoriaId == id);

            return View(await miContexto.ToListAsync());
        }
        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/
        [Authorize(Roles ="Empleado")]
        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Nombre");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Empleado")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,PrecioVigente,Activo,CategoriaId")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // GET: Productos/Edit/5
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Empleado")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,PrecioVigente,Activo,CategoriaId")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Nombre", producto.CategoriaId);
            return View(producto);
        }

        private bool ProductoExists(int id)
        {
            return _context.Productos.Any(e => e.Id == id);
        }
    }
}

CarritoCompras/Views/Productos/Create.cshtml
@model CarritoCompras.Models.Producto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nuevo Producto</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioVigente" class="control-label"></label>
                <input asp-for="PrecioVigente" class="form-control" />
                <span asp-validation-for="PrecioVigente" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>
                <select asp-for="CategoriaId" class ="form-control" asp-items="ViewBag.CategoriaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/Views/Productos/Details.cshtml
@model CarritoCompras.Models.Producto
@inject SignInManager<Usuario> signInManager

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioVigente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioVigente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>
    </dl>
</div>
<div>
    @if (Model.Activo && User.IsInRole("Cliente"))
    {

        <a asp-action="Create" asp-controller="CarritoItems" asp-route-prodId="@Model.Id" asp-route-user="@User.Identity.Name">Agregar a carrito |</a>

    }
    @if (User.IsInRole("Cliente") || !User.Identity.IsAuthenticated)
    {
        <a asp-action="MostrarProductosPorCategoria" asp-controller="Productos" asp-route-id="@Model.CategoriaId">Volver</a>
    }
    
    @if(User.IsInRole("Empleado"))
    {
        <a asp-action="Index">Volver</a>
    }
            
</div>

CarritoCompras/Views/Productos/Edit.cshtml
@model CarritoCompras.Models.Producto

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" readonly="readonly" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioVigente" class="control-label"></label>
                <input asp-for="PrecioVigente" class="form-control" />
                <span asp-validation-for="PrecioVigente" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>
                <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.CategoriaId"></select>
                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/Views/Productos/Index.cshtml
@model IEnumerable<CarritoCompras.Models.Producto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Productos</h1>

<p>
    <a asp-action="Create">Nuevo Producto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioVigente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioVigente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.Nombre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Create" asp-controller="StockItems" asp-route-id="@item.Id">Agregar a Sucursal</a>
            </td>
        </tr>
}
    </tbody>
</table>

CarritoCompras/Views/Productos/MostrarProductosPorCategoria.cshtml
@model IEnumerable<CarritoCompras.Models.Producto>
@inject SignInManager<Usuario> signInManager


@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Productos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioVigente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecioVigente)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                    @if (!signInManager.IsSignedIn(User))
                    {

                        <a asp-action="IniciarSesion" asp-controller="Accounts">Agregar a carrito</a>

                    }
                    else if (item.Activo)
                    {
                        <a asp-action="Create" asp-controller="CarritoItems" asp-route-prodId="@item.Id" asp-route-user="@User.Identity.Name">Agregar a carrito</a>
                    }
                    else
                    {
                        <a href="" style="color:black">Producto pausado</a>
                    }


                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Index" asp-controller="Categorias">Volver</a>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}