CarritoCompras/Models/CarritoItem.cs
using CarritoCompras.Data;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarritoCompras.Models
{

	public class CarritoItem
	{
		public int Id { get; set; }
		public Carrito Carrito { get; set; }
		public Producto Producto { get; set; }
		[NotMapped]
		[Range(0, double.MaxValue, ErrorMessage = ErrorMsgs.ErrorDeRange)]
		public double ValorUnitario { get; set; }
		[Required(ErrorMessage = ErrorMsgs.ErrorRequerido)]
		[Range(1, double.MaxValue, ErrorMessage = ErrorMsgs.ErrorMenorACero)]
		public int Cantidad { get; set; }
		[NotMapped]
		[Range(0.00, double.MaxValue, ErrorMessage = ErrorMsgs.ErrorMenorACero)]
		public double Subtotal { get; set; }

		
		public int CarritoId { get; set; }
	
		
		public int ProductoId { get; set; }
		
	}
}

CarritoCompras/Controllers/CarritoItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarritoCompras.Data;
using CarritoCompras.Models;
using Microsoft.AspNetCore.Identity;

namespace CarritoCompras.Controllers
{
    public class CarritoItemsController : Controller
    {
        private readonly MiContexto _context;
        private readonly UserManager<Usuario> _userManager;


        public CarritoItemsController(MiContexto context, UserManager<Usuario> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: CarritoItems
        public async Task<IActionResult> Index()
        {
            var miContexto = _context.CarritoItems.Include(c => c.Carrito).Include(c => c.Producto);
            return View(await miContexto.ToListAsync());
        }

        public async Task<IActionResult> MostrarCarrito(string email)
        {
            Usuario usr1 = _context.Usuarios.FirstOrDefault(u => u.Email == email);

            Carrito car1 = _context.Carritos.FirstOrDefault(c => c.ClienteId == usr1.Id && c.Activo == true);

            var miContexto = _context.CarritoItems.Where(c => c.CarritoId == car1.Id).Include(c => c.Producto);
            return View(await miContexto.ToListAsync());
        }

        // GET: CarritoItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carritoItem = await _context.CarritoItems
                .Include(c => c.Carrito)
                .Include(c => c.Producto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carritoItem == null)
            {
                return NotFound();
            }

            return View(carritoItem);
        }

        // GET: CarritoItems/Create
        public async Task<IActionResult> Create(int prodId, string user)
        {
            if (prodId != 0 && _context.Productos.FirstOrDefault(p => p.Id == prodId).Activo)
            {
                CarritoItem carritoItem = new CarritoItem();
                carritoItem.ProductoId = prodId;
                Usuario usr1 = _context.Usuarios.FirstOrDefault(u => u.Email == user);
                Carrito car1 = _context.Carritos.FirstOrDefault(c => c.ClienteId == usr1.Id && c.Activo);

                carritoItem.CarritoId = car1.Id;

                ViewData["ProductoId"] = prodId;
                ViewData["CarritoId"] = car1.Id;


                Producto proudctoEncontrado = _context.Productos.FirstOrDefault(p => p.Id == prodId);
                int categoriaId = proudctoEncontrado.CategoriaId;
                ViewData["categoriaId"] = categoriaId;


                return View("Create", carritoItem);
            }

            return RedirectToAction("MostrarProductosPorCategoria", "Productos", new { id = _context.Productos.FirstOrDefault(p => p.Id == prodId).CategoriaId });
        }

        // POST: CarritoItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Cantidad,CarritoId,ProductoId")] CarritoItem carritoItem)
        {
            CarritoItem car1 = new CarritoItem();
            car1.Cantidad = carritoItem.Cantidad;
            car1.ProductoId = carritoItem.ProductoId;
            car1.CarritoId = carritoItem.CarritoId;

            CarritoItem existe = _context.CarritoItems.FirstOrDefault(c => c.ProductoId == car1.ProductoId &&
                                                                        c.CarritoId == car1.CarritoId);

            if (ModelState.IsValid)
            {
                if (existe == null)
                { 
                    _context.CarritoItems.Add(car1);
                    _context.SaveChanges();
                } else
                {
                    existe.Cantidad += car1.Cantidad;
                    _context.CarritoItems.Update(existe);
                    _context.SaveChanges();
                }
            }

            Producto proudctoEncontrado = _context.Productos.FirstOrDefault(p => p.Id == carritoItem.ProductoId);
            int categoriaId = proudctoEncontrado.CategoriaId;

            return RedirectToAction("MostrarProductosPorCategoria", "Productos",new { id = categoriaId });
        }

        // GET: CarritoItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carritoItem = await _context.CarritoItems.FindAsync(id);
            if (carritoItem == null)
            {
                return NotFound();
            }
            ViewData["CarritoId"] = new SelectList(_context.Carritos, "Id", "Id", carritoItem.CarritoId);
            ViewData["ProductoId"] = new SelectList(_context.Productos, "Id", "Descripcion", carritoItem.ProductoId);

            //leo
            Producto productoEncontrado = _context.Productos.FirstOrDefault(p => p.Id == carritoItem.ProductoId);
            string nombreProd = productoEncontrado.Nombre;
            ViewData["ProductoNombre"] = nombreProd;
            //leo

            return View(carritoItem);
        }

        // POST: CarritoItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cantidad,CarritoId,ProductoId")] CarritoItem carritoItem)
        {
            if (id != carritoItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carritoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarritoItemExists(carritoItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                var car1 = _context.Carritos.FirstOrDefault(c => c.Id == carritoItem.CarritoId);
                var cli = _context.Usuarios.FirstOrDefault(c => c.Id == car1.ClienteId);            
                string email = cli.Email;
                return RedirectToAction("MostrarCarrito", new { email = email });
            }
            ViewData["CarritoId"] = new SelectList(_context.Carritos, "Id", "Id", carritoItem.CarritoId);
            ViewData["ProductoId"] = new SelectList(_context.Productos, "Id", "Descripcion", carritoItem.ProductoId);
            return View(carritoItem);
        }

        // GET: CarritoItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carritoItem = await _context.CarritoItems
                .Include(c => c.Carrito)
                .Include(c => c.Producto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carritoItem == null)
            {
                return NotFound();
            }

            Producto productoEncontrado = _context.Productos.FirstOrDefault(p => p.Id == carritoItem.ProductoId);
            string nombreProd = productoEncontrado.Nombre;
            ViewData["ProductoNombre"] = nombreProd;

            return View(carritoItem);
        }


        // POST: CarritoItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carritoItem = await _context.CarritoItems.FindAsync(id);
            _context.CarritoItems.Remove(carritoItem);
            await _context.SaveChangesAsync();


            var car1 = _context.Carritos.FirstOrDefault(c => c.Id == carritoItem.CarritoId);
            var cli = _context.Usuarios.FirstOrDefault(c => c.Id == car1.ClienteId);
            string email = cli.Email;
            return RedirectToAction("MostrarCarrito", new { email = email });
        }
        
        public async Task<IActionResult> VaciarCarrito(string userName)
        {
            Usuario userBuscado = _context.Usuarios.FirstOrDefault(u => u.Email == userName);      
            Carrito carritoDelUsuario = _context.Carritos.FirstOrDefault(c => c.ClienteId == userBuscado.Id);
            var listaDeCarritoItems = _context.CarritoItems.Where(c => c.CarritoId == carritoDelUsuario.Id).ToList();
            _context.CarritoItems.RemoveRange(listaDeCarritoItems);
            _context.SaveChanges();


            return RedirectToAction("MostrarCarrito", new { email = userName });
        }

        private bool CarritoItemExists(int id)
        {
            return _context.CarritoItems.Any(e => e.Id == id);
        }
              
    }
        
}

CarritoCompras/Views/CarritoItems/Create.cshtml
@model CarritoCompras.Models.CarritoItem

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Carrito</h1>

<h4>Agregar producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group d-none">
                <label asp-for="CarritoId" class="control-label"></label>
                <input asp-for="CarritoId" class="form-control" value=@ViewData["CarritoId"]/>
                <span asp-validation-for="CarritoId" class="text-danger"></span>
            </div>
            <div class="form-group d-none ">
                <label asp-for="ProductoId" class="control-label"></label>
                <input asp-for="ProductoId" class="form-control" value=@ViewData["ProductoId"] />
                <span asp-validation-for="ProductoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MostrarProductosPorCategoria" asp-controller="Productos" asp-route-id=@ViewData["categoriaId"] >Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/Views/CarritoItems/Delete.cshtml
@model CarritoCompras.Models.CarritoItem

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>
@{
    if (Model.Cantidad == 1)
    {
        <h3>¿Seguro que desea eliminar el producto?</h3>
    }
    else
    {
        <h3>¿Seguro que desea eliminar los productos?</h3>
    }
}
<div>
    <h4>@ViewData["ProductoNombre"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Producto.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="MostrarCarrito" asp-route-email="@User.Identity.Name">Volver al carrito</a>
    </form>
</div>

CarritoCompras/Views/CarritoItems/Details.cshtml
@model CarritoCompras.Models.CarritoItem

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>CarritoItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carrito)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carrito.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarritoCompras/Views/CarritoItems/Edit.cshtml
@model CarritoCompras.Models.CarritoItem

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Modificar cantidad</h1>

<h4>@ViewData["ProductoNombre"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CarritoId" class="control-label"></label>
                <select asp-for="CarritoId" class="form-control" asp-items="ViewBag.CarritoId"></select>
                <span asp-validation-for="CarritoId" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="ProductoId" class="control-label"></label>
                <select asp-for="ProductoId" class="form-control" asp-items="ViewBag.ProductoId"></select>
                <span asp-validation-for="ProductoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="MostrarCarrito" asp-route-email="@User.Identity.Name">Volver al carrito</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/Views/CarritoItems/Index.cshtml
@model IEnumerable<CarritoCompras.Models.CarritoItem>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Carrito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Carrito.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CarritoCompras/Views/CarritoItems/MostrarCarrito.cshtml
@model IEnumerable<CarritoCompras.Models.CarritoItem>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    double total = 0;
    foreach (var item in Model)
    {

        total = total + (item.Cantidad * item.Producto.PrecioVigente);
    }

}

<div class="col-8">
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Producto.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto.PrecioVigente)
            </th>
            <th>
                Parciales
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            double precioParcial = item.Cantidad * item.Producto.PrecioVigente;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.PrecioVigente)
                </td>
                <td>
                    @precioParcial.ToString("C")
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="col-11 mt-5">
    @if (total == 0)
    {
        <div class="text-center">No hay productos agregados en el carrito actualmente.</div>
    }
    else
    {        
        <div class="font-weight-bold text-right" style="font-size: 16px;">Subtotal: @total.ToString("C")</div>
        <div class="mt-4 text-right">
            <a asp-action="VaciarCarrito" asp-controller="CarritoItems" asp-route-userName="@User.Identity.Name"><i class="far fa-trash-alt"></i> Vaciar Carrito </a> |
            @if (total != 0)
            {
                <a asp-action="Index" asp-controller="Sucursales" asp-route-userName="@User.Identity.Name"> Finalizar Compra</a>
            }

        </div>
    }
</div>









@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}